### ISSUE TITLE
Bunch of shader errors

### ISSUE THREAD

**Issue by Firesampo** [swr06/Candela#2]
Hi,

This looks really promising. I tried to run it thru VS2022, unfortunately without success.

First I got an error about missing assimp-vc142mt.dll but I got that fixed by copying it directly to the output directory (did the same also for res/ and models/ folders), is this the expected way to run this?

Anyway, after that I got several shader compile errors, trying to run this on RTX 2080 based laptop.

![errors](https://user-images.githubusercontent.com/75070888/225441364-2c8fc27c-ed10-40d6-8f99-08784365c086.png)

Which VS version are you using?

**Comment by LDT9510** [comment]
I fixed it by renaming the global function `texture2DLod` to `textureLod` in `Core/Shaders/FXAA311.glsl`. Also better copy the executable from the build folder into the root of the project (where `Candela.sln` is at). Some build instructions would be nice haha. This project looks amazing, congrats to the author!

**Comment by swr06** [comment]
@XReaper95 Thankyou! I will definitely add some build instructions haha

@Firesampo Were you able to build this? If not, please add me on discord (swr#7777) I'd like to debug the issues further and push some fixes.

**Comment by Firesampo** [comment]
Yeah, got it to compile with the abovementioned textureLod + copying the exe trick - now it runs, but it flickers like crazy. Still getting these issues in the console (+ a zillion other errors, but these are the first ones):

![Screenshot 2023-03-16 164432](https://user-images.githubusercontent.com/75070888/225653992-ed6eed9b-b0d9-4433-8db4-8e62b052bde6.png)

I'll hit you up on Discord at some point today.

**Comment by swr06** [comment]
@Firesampo Thanks for bringing those up, I really want to try fixing those.

**Comment by Firesampo** [comment]
Sent a discord request (Sampoman)

**Comment by swr06** [comment]
@Firesampo I didn't recieve it, hm. Make sure you sent it to swr#7777

**Comment by Firesampo** [comment]
I did, try adding Sampoman#3096
